In [1]:
import pandas as pd
import numpy as np

from sklearn import linear_model
from sklearn import metrics

In [2]:
data = pd.read_csv('C:\\Users\\user\\AML_carownership\\household aggregate with unbinned trips and age.csv')

In [3]:
pd.set_option('max_columns', None)

In [4]:
data.head(5).append(data.tail(5))

,Unnamed: 0,HOUSEID,TRAVDAY,HOMEOWN,HHFAMINC,WALK,BIKE,TAXI,BUS,TRAIN,PRICE,PLACE,WALK2SAVE,BIKE2SAVE,PTRANS,HHRELATD,DRVRCNT,CNTTDHH,NUMADLT,YOUNGCHILD,WRKCOUNT,LIF_CYC,RAIL,URBAN,URBANSIZE,CDIVMSAR,WEBUSE17,SMPLSRCE,DRVRCNTPROP,WRKCOUNT_ratio,NUMADLT_ratio,YOUNGCHILD_ratio,HHSIZE_cleaned,VEHOWN,AVG_AGE,AVG_AGE_binned,HIGH_EDUC,FT_ratio,AVG_WORK_DIST,AVG_TIME,HEALTH,avg_trips,avg_trips_binned,one_job,flexible_work
0,0,30000012,5,HOME_OWN,10.0,2.0,Never,5,4,4,2.0,1.0,2.0,3.0,5.0,2,1,9,1.000000,0.0,1.000000,1,2,1,3,23,Daily,2,1.000000,1,1,0,1,1,45.000000,40 - 50,5.0,1,5-10 miles,20 - 30,2.0,9.000000,>5,1,1
1,1,30000082,3,HOME_RENT,8.0,NaN,Never,5,5,5,3.0,3.0,5.0,5.0,5.0,1,2,12,0.500000,0.5,0.500000,4,2,1,3,23,Daily,2,0.500000,>0.5,>0.5,>0.5,>2,1,38.500000,30 - 40,5.0,0.5,>15 miles,20 - 30,2.0,6.000000,>5,0.5,<0.5
2,2,30000130,1,HOME_OWN,5.0,NaN,NaN,-9,1,1,1.0,1.0,1.0,NaN,1.0,1,2,4,1.000000,0.0,1.000000,2,1,1,5,21,Daily,1,1.000000,1,1,0,2,1,45.000000,40 - 50,5.0,1,>15 miles,>30,3.0,2.000000,<=2,1,0.5
3,3,30000380,2,HOME_RENT,3.0,NaN,NaN,4,4,-9,1.0,NaN,NaN,NaN,NaN,1,2,18,0.666667,0.0,0.333333,6,2,1,1,23,Daily,2,0.666667,<0.5,>0.5,0,>2,1,37.333333,30 - 40,3.0,<0.5,<=5 miles,<=10,4.0,6.000000,>5,<0.5,<0.5
4,4,30000434,7,HOME_OWN,8.0,1.0,Rarely,5,5,4,NaN,2.0,2.0,3.0,3.0,1,2,6,1.000000,0.0,1.000000,2,2,4,6,23,Daily,2,1.000000,1,1,0,2,1,67.500000,>60,5.0,0.5,>15 miles,20 - 30,2.0,3.000000,2 - 3,1,0.5
17173,17173,40793685,1,HOME_OWN,5.0,NaN,NaN,-9,-9,-9,4.0,4.0,4.0,4.0,4.0,1,2,5,1.000000,0.0,0.000000,10,2,1,1,23,Daily,2,1.000000,0,1,0,2,1,67.500000,>60,3.0,non-work,Not Sure,non-work,3.0,2.500000,2 - 3,non-work,non-work
17174,17174,40793808,7,HOME_OWN,7.0,1.0,Rarely,5,4,5,3.0,3.0,3.0,3.0,3.0,1,2,16,0.666667,0.0,0.666667,8,2,1,1,23,Daily,2,0.666667,>0.5,>0.5,0,>2,1,42.000000,40 - 50,4.0,<0.5,<=5 miles,<=10,2.0,5.333333,>5,>0.5,<0.5
17175,17175,40793974,3,HOME_RENT,3.0,2.0,Never,5,5,5,1.0,2.0,3.0,3.0,3.0,2,1,7,1.000000,0.0,0.000000,9,2,1,1,23,Daily,2,1.000000,0,1,0,1,1,81.000000,>60,2.0,non-work,Not Sure,non-work,2.0,7.000000,>5,non-work,non-work
17176,17176,40794020,3,HOME_OWN,8.0,4.0,Never,5,4,5,2.0,2.0,5.0,5.0,5.0,1,2,11,1.000000,0.0,0.000000,10,2,4,6,24,Daily,2,1.000000,0,1,0,2,1,72.500000,>60,3.0,non-work,Not Sure,non-work,3.0,5.500000,>5,non-work,non-work
17177,17177,40794249,2,HOME_RENT,2.0,4.0,Never,5,5,5,3.0,3.0,3.0,5.0,5.0,2,1,2,1.000000,0.0,0.000000,9,2,2,6,23,Never,2,1.000000,0,1,0,1,0,80.000000,>60,2.0,non-work,Not Sure,non-work,3.0,2.000000,<=2,non-work,non-work

In [5]:
data.shape

(17178, 45)

In [6]:
data_ = data.copy()

In [7]:
data['DRVRCNTPROP'].value_counts()

1.000000    12090
0.500000     1831
0.000000     1072
0.666667     1020
0.333333      291
0.750000      269
0.400000      261
0.600000       95
0.250000       80
0.800000       60
0.200000       29
0.428571       14
0.285714       14
0.166667       11
0.833333        9
0.571429        7
0.142857        5
0.375000        5
0.222222        3
0.714286        3
0.300000        2
0.125000        1
0.555556        1
0.111111        1
0.625000        1
0.272727        1
0.700000        1
0.857143        1
Name: DRVRCNTPROP, dtype: int64

In [8]:
data['DRVRCNTPROP_binned'] = 'NA'
data.loc[data['DRVRCNTPROP']==0,'DRVRCNTPROP_binned'] ='0'
data.loc[data['DRVRCNTPROP'].between(0,0.5,inclusive = False),'DRVRCNTPROP_binned'] = '<0.5'
data.loc[data['DRVRCNTPROP'].between(0.5,1, inclusive = False),'DRVRCNTPROP_binned'] = '>0.5'
data.loc[data['DRVRCNTPROP']==1,'DRVRCNTPROP_binned'] ='1'
data.loc[data['DRVRCNTPROP']==0.5,'DRVRCNTPROP_binned'] ='0.5'
data
data_im = data[['HOUSEID','DRVRCNTPROP','DRVRCNTPROP_binned']]

In [9]:
data_im.head(5).append(data_im.tail(5))

        HOUSEID  DRVRCNTPROP DRVRCNTPROP_binned
0      30000012     1.000000                  1
1      30000082     0.500000                0.5
2      30000130     1.000000                  1
3      30000380     0.666667               >0.5
4      30000434     1.000000                  1
17173  40793685     1.000000                  1
17174  40793808     0.666667               >0.5
17175  40793974     1.000000                  1
17176  40794020     1.000000                  1
17177  40794249     1.000000                  1

In [10]:
data.head(5).append(data.tail(5))

,Unnamed: 0,HOUSEID,TRAVDAY,HOMEOWN,HHFAMINC,WALK,BIKE,TAXI,BUS,TRAIN,PRICE,PLACE,WALK2SAVE,BIKE2SAVE,PTRANS,HHRELATD,DRVRCNT,CNTTDHH,NUMADLT,YOUNGCHILD,WRKCOUNT,LIF_CYC,RAIL,URBAN,URBANSIZE,CDIVMSAR,WEBUSE17,SMPLSRCE,DRVRCNTPROP,WRKCOUNT_ratio,NUMADLT_ratio,YOUNGCHILD_ratio,HHSIZE_cleaned,VEHOWN,AVG_AGE,AVG_AGE_binned,HIGH_EDUC,FT_ratio,AVG_WORK_DIST,AVG_TIME,HEALTH,avg_trips,avg_trips_binned,one_job,flexible_work,DRVRCNTPROP_binned
0,0,30000012,5,HOME_OWN,10.0,2.0,Never,5,4,4,2.0,1.0,2.0,3.0,5.0,2,1,9,1.000000,0.0,1.000000,1,2,1,3,23,Daily,2,1.000000,1,1,0,1,1,45.000000,40 - 50,5.0,1,5-10 miles,20 - 30,2.0,9.000000,>5,1,1,1
1,1,30000082,3,HOME_RENT,8.0,NaN,Never,5,5,5,3.0,3.0,5.0,5.0,5.0,1,2,12,0.500000,0.5,0.500000,4,2,1,3,23,Daily,2,0.500000,>0.5,>0.5,>0.5,>2,1,38.500000,30 - 40,5.0,0.5,>15 miles,20 - 30,2.0,6.000000,>5,0.5,<0.5,0.5
2,2,30000130,1,HOME_OWN,5.0,NaN,NaN,-9,1,1,1.0,1.0,1.0,NaN,1.0,1,2,4,1.000000,0.0,1.000000,2,1,1,5,21,Daily,1,1.000000,1,1,0,2,1,45.000000,40 - 50,5.0,1,>15 miles,>30,3.0,2.000000,<=2,1,0.5,1
3,3,30000380,2,HOME_RENT,3.0,NaN,NaN,4,4,-9,1.0,NaN,NaN,NaN,NaN,1,2,18,0.666667,0.0,0.333333,6,2,1,1,23,Daily,2,0.666667,<0.5,>0.5,0,>2,1,37.333333,30 - 40,3.0,<0.5,<=5 miles,<=10,4.0,6.000000,>5,<0.5,<0.5,>0.5
4,4,30000434,7,HOME_OWN,8.0,1.0,Rarely,5,5,4,NaN,2.0,2.0,3.0,3.0,1,2,6,1.000000,0.0,1.000000,2,2,4,6,23,Daily,2,1.000000,1,1,0,2,1,67.500000,>60,5.0,0.5,>15 miles,20 - 30,2.0,3.000000,2 - 3,1,0.5,1
17173,17173,40793685,1,HOME_OWN,5.0,NaN,NaN,-9,-9,-9,4.0,4.0,4.0,4.0,4.0,1,2,5,1.000000,0.0,0.000000,10,2,1,1,23,Daily,2,1.000000,0,1,0,2,1,67.500000,>60,3.0,non-work,Not Sure,non-work,3.0,2.500000,2 - 3,non-work,non-work,1
17174,17174,40793808,7,HOME_OWN,7.0,1.0,Rarely,5,4,5,3.0,3.0,3.0,3.0,3.0,1,2,16,0.666667,0.0,0.666667,8,2,1,1,23,Daily,2,0.666667,>0.5,>0.5,0,>2,1,42.000000,40 - 50,4.0,<0.5,<=5 miles,<=10,2.0,5.333333,>5,>0.5,<0.5,>0.5
17175,17175,40793974,3,HOME_RENT,3.0,2.0,Never,5,5,5,1.0,2.0,3.0,3.0,3.0,2,1,7,1.000000,0.0,0.000000,9,2,1,1,23,Daily,2,1.000000,0,1,0,1,1,81.000000,>60,2.0,non-work,Not Sure,non-work,2.0,7.000000,>5,non-work,non-work,1
17176,17176,40794020,3,HOME_OWN,8.0,4.0,Never,5,4,5,2.0,2.0,5.0,5.0,5.0,1,2,11,1.000000,0.0,0.000000,10,2,4,6,24,Daily,2,1.000000,0,1,0,2,1,72.500000,>60,3.0,non-work,Not Sure,non-work,3.0,5.500000,>5,non-work,non-work,1
17177,17177,40794249,2,HOME_RENT,2.0,4.0,Never,5,5,5,3.0,3.0,3.0,5.0,5.0,2,1,2,1.000000,0.0,0.000000,9,2,2,6,23,Never,2,1.000000,0,1,0,1,0,80.000000,>60,2.0,non-work,Not Sure,non-work,3.0,2.000000,<=2,non-work,non-work,1

In [11]:
data.shape

(17178, 46)

In [12]:
data_copy=data.copy()

In [13]:
data['TRAIN'].value_counts()

 5    9859
 4    4002
-9    1599
 1     668
 3     597
 2     451
-7       2
Name: TRAIN, dtype: int64

In [14]:
#replace -7, -8, -9 in TAXI, BUS, TRAIN to NA
data['TRAIN']= data['TRAIN'].replace([-7, -8, -9], np.nan)#'NaN')
data['TAXI'] = data['TAXI'].replace([-7, -8, -9], np.nan)#'NaN')
data['BUS'] = data['BUS'].replace([-7, -8, -9], np.nan)#'NaN')

In [15]:
data['TAXI'].value_counts()

5.0    10444
4.0     3804
3.0      870
2.0      297
1.0       60
Name: TAXI, dtype: int64

In [16]:
data.shape

(17178, 46)

In [17]:
#data = data.loc[data['TRAIN'] != 'NaN']
#data.shape

In [18]:
#data = data.loc[data['TAXI'] != 'NaN']
#data.shape

In [19]:
#data = data.loc[data['BUS'] != 'NaN']
#data.shape

In [20]:
#data.loc[data['BUS']==-9]

In [21]:
#data.where(data == -9).sum()

In [22]:
data_= data.dropna(how='any')

In [23]:
data_copy1=data_.copy()

In [24]:
data.shape, data_.shape

((17178, 46), (13892, 46))

In [25]:
data_['TAXI'].value_counts()

5.0    9467
4.0    3426
3.0     724
2.0     237
1.0      38
Name: TAXI, dtype: int64

In [26]:
data_['BUS'].value_counts()

5.0    10059
4.0     2449
3.0      545
2.0      455
1.0      384
Name: BUS, dtype: int64

In [27]:
data_.isna().values.sum()

0

In [28]:
col = ['BUS', 'TAXI', 'TAXI']
data_[col]

       BUS  TAXI  TAXI
0      4.0   5.0   5.0
5      5.0   4.0   4.0
6      5.0   5.0   5.0
7      5.0   5.0   5.0
8      5.0   5.0   5.0
9      5.0   5.0   5.0
11     4.0   3.0   3.0
12     5.0   5.0   5.0
13     5.0   5.0   5.0
14     1.0   4.0   4.0
17     1.0   4.0   4.0
18     5.0   5.0   5.0
19     5.0   5.0   5.0
20     5.0   5.0   5.0
21     5.0   5.0   5.0
22     2.0   2.0   2.0
23     5.0   5.0   5.0
24     5.0   5.0   5.0
25     5.0   5.0   5.0
26     5.0   4.0   4.0
28     5.0   5.0   5.0
29     5.0   5.0   5.0
30     2.0   5.0   5.0
32     5.0   5.0   5.0
33     5.0   5.0   5.0
34     5.0   5.0   5.0
35     5.0   5.0   5.0
36     4.0   5.0   5.0
37     5.0   5.0   5.0
39     5.0   5.0   5.0
...    ...   ...   ...
17137  4.0   5.0   5.0
17140  4.0   3.0   3.0
17141  3.0   4.0   4.0
17145  5.0   4.0   4.0
17146  5.0   5.0   5.0
17147  5.0   5.0   5.0
17148  5.0   5.0   5.0
17149  5.0   5.0   5.0
17151  5.0   5.0   5.0
17152  5.0   5.0   5.0
17153  5.0   5.0   5.0
17154  4.0   4.0   4.0
17156  5.0   5.0   5.0
17157  3.0   5.0   5.0
17158  4.0   4.0   4.0
17159  5.0   5.0   5.0
17161  4.0   5.0   5.0
17162  4.0   3.0   3.0
17163  5.0   5.0   5.0
17166  2.0   4.0   4.0
17167  5.0   5.0   5.0
17168  5.0   4.0   4.0
17169  2.0   5.0   5.0
17170  5.0   5.0   5.0
17171  4.0   5.0   5.0
17172  5.0   5.0   5.0
17174  4.0   5.0   5.0
17175  5.0   5.0   5.0
17176  4.0   5.0   5.0
17177  5.0   5.0   5.0

[13892 rows x 3 columns]

In [29]:
full_list=data_.columns.tolist()
full_list

['Unnamed: 0',
 'HOUSEID',
 'TRAVDAY',
 'HOMEOWN',
 'HHFAMINC',
 'WALK',
 'BIKE',
 'TAXI',
 'BUS',
 'TRAIN',
 'PRICE',
 'PLACE',
 'WALK2SAVE',
 'BIKE2SAVE',
 'PTRANS',
 'HHRELATD',
 'DRVRCNT',
 'CNTTDHH',
 'NUMADLT',
 'YOUNGCHILD',
 'WRKCOUNT',
 'LIF_CYC',
 'RAIL',
 'URBAN',
 'URBANSIZE',
 'CDIVMSAR',
 'WEBUSE17',
 'SMPLSRCE',
 'DRVRCNTPROP',
 'WRKCOUNT_ratio',
 'NUMADLT_ratio',
 'YOUNGCHILD_ratio',
 'HHSIZE_cleaned',
 'VEHOWN',
 'AVG_AGE',
 'AVG_AGE_binned',
 'HIGH_EDUC',
 'FT_ratio',
 'AVG_WORK_DIST',
 'AVG_TIME',
 'HEALTH',
 'avg_trips',
 'avg_trips_binned',
 'one_job',
 'flexible_work',
 'DRVRCNTPROP_binned']

In [30]:
cols = ['Unnamed: 0', 'VEHOWN']
full_list.remove('Unnamed: 0')
full_list.remove('VEHOWN')

In [31]:
y = data_['VEHOWN']

In [32]:
data_['WEBUSE17'].value_counts()

Daily     12218
Rarely      928
Never       746
Name: WEBUSE17, dtype: int64

In [33]:
X=data_.loc[:,full_list]

In [34]:
selected_column =  ['HOMEOWN', 'HHFAMINC', 'PRICE', 'BIKE', 'WEBUSE17', 'WRKCOUNT_ratio', 'NUMADLT_ratio', \
                    'YOUNGCHILD_ratio', 'HHSIZE_cleaned', 'AVG_AGE_binned', 'FT_ratio', 'AVG_WORK_DIST', 'AVG_TIME', \
                   'one_job', 'flexible_work', 'DRVRCNTPROP_binned', 'avg_trips_binned']

In [35]:
data_[selected_column].head(5)

,HOMEOWN,HHFAMINC,PRICE,BIKE,WEBUSE17,WRKCOUNT_ratio,NUMADLT_ratio,YOUNGCHILD_ratio,HHSIZE_cleaned,AVG_AGE_binned,FT_ratio,AVG_WORK_DIST,AVG_TIME,one_job,flexible_work,DRVRCNTPROP_binned,avg_trips_binned
0,HOME_OWN,10.0,2.0,Never,Daily,1,1,0,1,40 - 50,1,5-10 miles,20 - 30,1,1,1,>5
5,HOME_OWN,9.0,3.0,Never,Daily,>0.5,1,0,2,>60,0.5,<=5 miles,<=10,0.5,0,0.5,<=2
6,HOME_OWN,8.0,1.0,Daily,Daily,>0.5,1,0,>2,30 - 40,<0.5,10 - 15 miles,20 - 30,0.5,<0.5,1,<=2
7,HOME_RENT,3.0,1.0,Never,Daily,1,1,0,1,>60,0,<=5 miles,<=10,1,0,1,>5
8,HOME_OWN,8.0,4.0,Never,Rarely,>0.5,1,0,2,>60,0.5,Not Sure,non-work,0.5,0,0.5,2 - 3

In [36]:
y.head(5)

0    1
5    1
6    1
7    1
8    1
Name: VEHOWN, dtype: int64

In [37]:
data_['HOMEOWN'] = data_['HOMEOWN'].astype('category')
data_['BIKE'] = data_['BIKE'].astype('category')
data_['WEBUSE17'] =data_['WEBUSE17'].astype('category')
data_['WRKCOUNT_ratio'] =data_['WRKCOUNT_ratio'].astype('category')
data_['NUMADLT_ratio'] =data_['NUMADLT_ratio'].astype('category')
data_['YOUNGCHILD_ratio'] =data_['YOUNGCHILD_ratio'].astype('category')
data_['HHSIZE_cleaned'] =data_['HHSIZE_cleaned'].astype('category')
data_['AVG_AGE_binned'] =data_['AVG_AGE_binned'].astype('category')
data_['FT_ratio'] =data_['FT_ratio'].astype('category')
data_['AVG_WORK_DIST'] =data_['AVG_WORK_DIST'].astype('category')
data_['AVG_TIME'] =data_['AVG_TIME'].astype('category')
data_['one_job'] =data_['one_job'].astype('category')
data_['flexible_work'] =data_['flexible_work'].astype('category')
data_['DRVRCNTPROP_binned'] =data_['DRVRCNTPROP_binned'].astype('category')
data_['avg_trips_binned'] =data_['avg_trips_binned'].astype('category')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [38]:
# Assigning numerical values and storing in another column
data_['HOMEOWN_CAT'] = data_['HOMEOWN'].cat.codes
data_['BIKE_CAT'] = data_['BIKE'].cat.codes
data_['WEBUSE17_CAT'] = data_['WEBUSE17'].cat.codes
data_['WRKCOUNT_ratio_CAT'] =data_['WRKCOUNT_ratio'].cat.codes
data_['NUMADLT_ratio_CAT'] =data_['NUMADLT_ratio'].cat.codes
data_['YOUNGCHILD_ratio_CAT'] =data_['YOUNGCHILD_ratio'].cat.codes
data_['HHSIZE_cleaned_CAT'] =data_['HHSIZE_cleaned'].cat.codes
data_['AVG_AGE_binned_CAT'] =data_['AVG_AGE_binned'].cat.codes
data_['FT_ratio_CAT'] =data_['FT_ratio'].cat.codes
data_['AVG_WORK_DIST_CAT'] =data_['AVG_WORK_DIST'].cat.codes
data_['AVG_TIME_CAT'] =data_['AVG_TIME'].cat.codes
data_['one_job_CAT'] =data_['one_job'].cat.codes
data_['flexible_work_CAT'] =data_['flexible_work'].cat.codes
data_['DRVRCNTPROP_binned_CAT'] =data_['DRVRCNTPROP_binned'].cat.codes
data_['avg_trips_binned_CAT'] =data_['avg_trips_binned'].cat.codes
data_.head(5)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

,Unnamed: 0,HOUSEID,TRAVDAY,HOMEOWN,HHFAMINC,WALK,BIKE,TAXI,BUS,TRAIN,PRICE,PLACE,WALK2SAVE,BIKE2SAVE,PTRANS,HHRELATD,DRVRCNT,CNTTDHH,NUMADLT,YOUNGCHILD,WRKCOUNT,LIF_CYC,RAIL,URBAN,URBANSIZE,CDIVMSAR,WEBUSE17,SMPLSRCE,DRVRCNTPROP,WRKCOUNT_ratio,NUMADLT_ratio,YOUNGCHILD_ratio,HHSIZE_cleaned,VEHOWN,AVG_AGE,AVG_AGE_binned,HIGH_EDUC,FT_ratio,AVG_WORK_DIST,AVG_TIME,HEALTH,avg_trips,avg_trips_binned,one_job,flexible_work,DRVRCNTPROP_binned,HOMEOWN_CAT,BIKE_CAT,WEBUSE17_CAT,WRKCOUNT_ratio_CAT,NUMADLT_ratio_CAT,YOUNGCHILD_ratio_CAT,HHSIZE_cleaned_CAT,AVG_AGE_binned_CAT,FT_ratio_CAT,AVG_WORK_DIST_CAT,AVG_TIME_CAT,one_job_CAT,flexible_work_CAT,DRVRCNTPROP_binned_CAT,avg_trips_binned_CAT
0,0,30000012,5,HOME_OWN,10.0,2.0,Never,5.0,4.0,4.0,2.0,1.0,2.0,3.0,5.0,2,1,9,1.0,0.0,1.0,1,2,1,3,23,Daily,2,1.0,1,1,0,1,1,45.00,40 - 50,5.0,1,5-10 miles,20 - 30,2.0,9.0,>5,1,1,1,0,1,0,1,0,0,0,1,2,1,1,2,2,2,4
5,5,30000436,5,HOME_OWN,9.0,5.0,Never,4.0,5.0,5.0,3.0,3.0,5.0,5.0,5.0,1,1,3,1.0,0.0,0.5,10,2,1,1,23,Daily,2,0.5,>0.5,1,0,2,1,75.50,>60,4.0,0.5,<=5 miles,<=10,4.0,1.5,<=2,0.5,0,0.5,0,1,0,3,0,0,1,4,1,2,2,1,0,1,3
6,6,30000439,7,HOME_OWN,8.0,1.0,Daily,5.0,5.0,4.0,1.0,1.0,2.0,2.0,3.0,1,>2,6,1.0,0.0,0.5,8,1,4,6,21,Daily,2,1.0,>0.5,1,0,>2,1,37.75,30 - 40,5.0,<0.5,10 - 15 miles,20 - 30,4.0,1.5,<=2,0.5,<0.5,1,0,0,0,3,0,0,2,0,3,0,1,1,3,2,3
7,7,30000473,7,HOME_RENT,3.0,5.0,Never,5.0,5.0,5.0,1.0,3.0,5.0,5.0,5.0,2,1,8,1.0,0.0,1.0,9,2,1,1,23,Daily,2,1.0,1,1,0,1,1,66.00,>60,3.0,0,<=5 miles,<=10,4.0,8.0,>5,1,0,1,1,1,0,1,0,0,0,4,0,2,2,2,0,2,4
8,8,30000496,7,HOME_OWN,8.0,4.0,Never,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,1,1,6,1.0,0.0,0.5,10,1,1,5,21,Rarely,2,0.5,>0.5,1,0,2,1,75.00,>60,5.0,0.5,Not Sure,non-work,4.0,3.0,2 - 3,0.5,0,0.5,0,1,2,3,0,0,1,4,1,4,4,1,0,1,0

In [39]:
data_.columns.tolist()

['Unnamed: 0',
 'HOUSEID',
 'TRAVDAY',
 'HOMEOWN',
 'HHFAMINC',
 'WALK',
 'BIKE',
 'TAXI',
 'BUS',
 'TRAIN',
 'PRICE',
 'PLACE',
 'WALK2SAVE',
 'BIKE2SAVE',
 'PTRANS',
 'HHRELATD',
 'DRVRCNT',
 'CNTTDHH',
 'NUMADLT',
 'YOUNGCHILD',
 'WRKCOUNT',
 'LIF_CYC',
 'RAIL',
 'URBAN',
 'URBANSIZE',
 'CDIVMSAR',
 'WEBUSE17',
 'SMPLSRCE',
 'DRVRCNTPROP',
 'WRKCOUNT_ratio',
 'NUMADLT_ratio',
 'YOUNGCHILD_ratio',
 'HHSIZE_cleaned',
 'VEHOWN',
 'AVG_AGE',
 'AVG_AGE_binned',
 'HIGH_EDUC',
 'FT_ratio',
 'AVG_WORK_DIST',
 'AVG_TIME',
 'HEALTH',
 'avg_trips',
 'avg_trips_binned',
 'one_job',
 'flexible_work',
 'DRVRCNTPROP_binned',
 'HOMEOWN_CAT',
 'BIKE_CAT',
 'WEBUSE17_CAT',
 'WRKCOUNT_ratio_CAT',
 'NUMADLT_ratio_CAT',
 'YOUNGCHILD_ratio_CAT',
 'HHSIZE_cleaned_CAT',
 'AVG_AGE_binned_CAT',
 'FT_ratio_CAT',
 'AVG_WORK_DIST_CAT',
 'AVG_TIME_CAT',
 'one_job_CAT',
 'flexible_work_CAT',
 'DRVRCNTPROP_binned_CAT',
 'avg_trips_binned_CAT']

In [40]:
#'TAXI', 'BUS', 'TRAIN', 
selected_column1 =  ['HHFAMINC', 'WALK', 'TAXI', 'BUS', 'TRAIN', 'PRICE', 'PLACE', 'WALK2SAVE', \
                     'BIKE2SAVE', 'PTRANS', 'HHRELATD', 'CNTTDHH', 'LIF_CYC', \
                     'RAIL', 'URBAN','URBANSIZE','CDIVMSAR', 'HIGH_EDUC', 'HEALTH', \
                     'HOMEOWN_CAT', 'BIKE_CAT', 'WEBUSE17_CAT', 'WRKCOUNT_ratio_CAT', 'NUMADLT_ratio_CAT', \
                     'YOUNGCHILD_ratio_CAT', 'HHSIZE_cleaned_CAT',\
                     'FT_ratio_CAT', 'AVG_WORK_DIST_CAT', 'AVG_AGE_binned_CAT', 'one_job_CAT', 'flexible_work_CAT',\
                    'DRVRCNTPROP_binned_CAT', 'avg_trips_binned_CAT']

In [41]:
#high_score_features1 = []
#feature_scores = mutual_info_classif(X, y, random_state=0, n_neighbors=3,discrete_features=discrete_feat_idx)
#for score, f_name in sorted(zip(feature_scores, X.columns), reverse=True)[:threshold]:
#        print(f_name, score)
#        high_score_features1.append(f_name)

#feature_scores

In [42]:
#numeric variables: CNTTDHH, NUMADLT, YOUNGCHILD, WRKCOUNT
X=data_.loc[:,selected_column1]
X.head(5).append(X.tail(5))

,HHFAMINC,WALK,TAXI,BUS,TRAIN,PRICE,PLACE,WALK2SAVE,BIKE2SAVE,PTRANS,HHRELATD,CNTTDHH,LIF_CYC,RAIL,URBAN,URBANSIZE,CDIVMSAR,HIGH_EDUC,HEALTH,HOMEOWN_CAT,BIKE_CAT,WEBUSE17_CAT,WRKCOUNT_ratio_CAT,NUMADLT_ratio_CAT,YOUNGCHILD_ratio_CAT,HHSIZE_cleaned_CAT,FT_ratio_CAT,AVG_WORK_DIST_CAT,AVG_AGE_binned_CAT,one_job_CAT,flexible_work_CAT,DRVRCNTPROP_binned_CAT,avg_trips_binned_CAT
0,10.0,2.0,5.0,4.0,4.0,2.0,1.0,2.0,3.0,5.0,2,9,1,2,1,3,23,5.0,2.0,0,1,0,1,0,0,0,2,1,1,2,2,2,4
5,9.0,5.0,4.0,5.0,5.0,3.0,3.0,5.0,5.0,5.0,1,3,10,2,1,1,23,4.0,4.0,0,1,0,3,0,0,1,1,2,4,1,0,1,3
6,8.0,1.0,5.0,5.0,4.0,1.0,1.0,2.0,2.0,3.0,1,6,8,1,4,6,21,5.0,4.0,0,0,0,3,0,0,2,3,0,0,1,3,2,3
7,3.0,5.0,5.0,5.0,5.0,1.0,3.0,5.0,5.0,5.0,2,8,9,2,1,1,23,3.0,4.0,1,1,0,1,0,0,0,0,2,4,2,0,2,4
8,8.0,4.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,1,6,10,1,1,5,21,5.0,4.0,0,1,2,3,0,0,1,1,4,4,1,0,1,0
17172,8.0,3.0,5.0,5.0,5.0,4.0,2.0,3.0,5.0,5.0,1,8,6,2,1,3,23,5.0,2.0,0,1,0,3,2,0,2,3,2,3,1,3,1,3
17174,7.0,1.0,5.0,4.0,5.0,3.0,3.0,3.0,3.0,3.0,1,16,8,2,1,1,23,4.0,2.0,0,2,0,3,2,0,2,3,2,1,4,3,4,4
17175,3.0,2.0,5.0,5.0,5.0,1.0,2.0,3.0,3.0,3.0,2,7,9,2,1,1,23,2.0,2.0,1,1,0,0,0,0,0,5,4,4,5,4,2,4
17176,8.0,4.0,5.0,4.0,5.0,2.0,2.0,5.0,5.0,5.0,1,11,10,2,4,6,24,3.0,3.0,0,1,0,0,0,0,1,5,4,4,5,4,2,4
17177,2.0,4.0,5.0,5.0,5.0,3.0,3.0,3.0,5.0,5.0,2,2,9,2,2,6,23,2.0,3.0,1,1,1,0,0,0,0,5,4,4,5,4,2,3

In [43]:
list1=X.columns.tolist()
list1.remove('CNTTDHH')
#list1.remove('NUMADLT')
#list1.remove('YOUNGCHILD')
#list1.remove('WRKCOUNT')
#list1.remove('DRVRCNTPROP')
#list1.remove('avg_trips')

In [44]:
#index_no = X.columns.get_loc(list1)
a = [X.columns.get_loc(col) for col in list1]

In [45]:
print(*a, sep = ", ")

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32

In [46]:
X.shape, y.shape

((13892, 33), (13892,))

In [47]:
y.dropna(how='any', inplace=True)

In [48]:
X=data_.loc[:,selected_column1]

In [49]:
X.head(5).append(X.tail(5))

,HHFAMINC,WALK,TAXI,BUS,TRAIN,PRICE,PLACE,WALK2SAVE,BIKE2SAVE,PTRANS,HHRELATD,CNTTDHH,LIF_CYC,RAIL,URBAN,URBANSIZE,CDIVMSAR,HIGH_EDUC,HEALTH,HOMEOWN_CAT,BIKE_CAT,WEBUSE17_CAT,WRKCOUNT_ratio_CAT,NUMADLT_ratio_CAT,YOUNGCHILD_ratio_CAT,HHSIZE_cleaned_CAT,FT_ratio_CAT,AVG_WORK_DIST_CAT,AVG_AGE_binned_CAT,one_job_CAT,flexible_work_CAT,DRVRCNTPROP_binned_CAT,avg_trips_binned_CAT
0,10.0,2.0,5.0,4.0,4.0,2.0,1.0,2.0,3.0,5.0,2,9,1,2,1,3,23,5.0,2.0,0,1,0,1,0,0,0,2,1,1,2,2,2,4
5,9.0,5.0,4.0,5.0,5.0,3.0,3.0,5.0,5.0,5.0,1,3,10,2,1,1,23,4.0,4.0,0,1,0,3,0,0,1,1,2,4,1,0,1,3
6,8.0,1.0,5.0,5.0,4.0,1.0,1.0,2.0,2.0,3.0,1,6,8,1,4,6,21,5.0,4.0,0,0,0,3,0,0,2,3,0,0,1,3,2,3
7,3.0,5.0,5.0,5.0,5.0,1.0,3.0,5.0,5.0,5.0,2,8,9,2,1,1,23,3.0,4.0,1,1,0,1,0,0,0,0,2,4,2,0,2,4
8,8.0,4.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,4.0,1,6,10,1,1,5,21,5.0,4.0,0,1,2,3,0,0,1,1,4,4,1,0,1,0
17172,8.0,3.0,5.0,5.0,5.0,4.0,2.0,3.0,5.0,5.0,1,8,6,2,1,3,23,5.0,2.0,0,1,0,3,2,0,2,3,2,3,1,3,1,3
17174,7.0,1.0,5.0,4.0,5.0,3.0,3.0,3.0,3.0,3.0,1,16,8,2,1,1,23,4.0,2.0,0,2,0,3,2,0,2,3,2,1,4,3,4,4
17175,3.0,2.0,5.0,5.0,5.0,1.0,2.0,3.0,3.0,3.0,2,7,9,2,1,1,23,2.0,2.0,1,1,0,0,0,0,0,5,4,4,5,4,2,4
17176,8.0,4.0,5.0,4.0,5.0,2.0,2.0,5.0,5.0,5.0,1,11,10,2,4,6,24,3.0,3.0,0,1,0,0,0,0,1,5,4,4,5,4,2,4
17177,2.0,4.0,5.0,5.0,5.0,3.0,3.0,3.0,5.0,5.0,2,2,9,2,2,6,23,2.0,3.0,1,1,1,0,0,0,0,5,4,4,5,4,2,3

In [50]:
#selected_column2= ['HHFAMINC','WALK','TAXI','BUS','TRAIN','CNTTDHH']

In [51]:
#col = ['TAXI', 'TRAIN', 'BUS']
#X[col].dropna(how='any',inplace=True)
#X['TAXI'].value_counts()

In [52]:
#X['BUS'].value_counts()

In [53]:
from functools import partial
from sklearn.feature_selection import mutual_info_classif, SelectKBest
#X=data_.loc[:,selected_column1]
discrete_feat_idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
#[0, 1, 2, 3, 4, 5, 6, 7, 12, 13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
score_func = partial(mutual_info_classif, discrete_features=discrete_feat_idx)
s = SelectKBest(score_func=score_func, k='all')

In [54]:
fit = s.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

In [55]:
#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Selected_Columns','Score'] 
print(featureScores.nlargest(40,'Score'))  #print 10 best features

          Selected_Columns     Score
31  DRVRCNTPROP_binned_CAT  0.128880
3                      BUS  0.073306
19             HOMEOWN_CAT  0.064241
2                     TAXI  0.057704
9                   PTRANS  0.057204
0                 HHFAMINC  0.046978
7                WALK2SAVE  0.039340
1                     WALK  0.039292
4                    TRAIN  0.033921
12                 LIF_CYC  0.027486
10                HHRELATD  0.023519
25      HHSIZE_cleaned_CAT  0.021922
15               URBANSIZE  0.018956
27       AVG_WORK_DIST_CAT  0.016590
14                   URBAN  0.015809
17               HIGH_EDUC  0.015264
26            FT_ratio_CAT  0.012973
11                 CNTTDHH  0.011544
29             one_job_CAT  0.011392
8                BIKE2SAVE  0.011242
22      WRKCOUNT_ratio_CAT  0.011151
30       flexible_work_CAT  0.011056
5                    PRICE  0.009486
16                CDIVMSAR  0.008727
13                    RAIL  0.008549
21            WEBUSE17_CAT  0.007583
18                  HEALTH  0.006679
6                    PLACE  0.004353
20                BIKE_CAT  0.003393
23       NUMADLT_ratio_CAT  0.002400
32    avg_trips_binned_CAT  0.001760
28      AVG_AGE_binned_CAT  0.001033
24    YOUNGCHILD_ratio_CAT  0.000581

In [56]:
#we choose those variables with score greater than 0.01
featureScores['Selected_Columns'][featureScores['Score']>0.01].tolist()

['HHFAMINC',
 'WALK',
 'TAXI',
 'BUS',
 'TRAIN',
 'WALK2SAVE',
 'BIKE2SAVE',
 'PTRANS',
 'HHRELATD',
 'CNTTDHH',
 'LIF_CYC',
 'URBAN',
 'URBANSIZE',
 'HIGH_EDUC',
 'HOMEOWN_CAT',
 'WRKCOUNT_ratio_CAT',
 'HHSIZE_cleaned_CAT',
 'FT_ratio_CAT',
 'AVG_WORK_DIST_CAT',
 'one_job_CAT',
 'flexible_work_CAT',
 'DRVRCNTPROP_binned_CAT']

In [ ]:
len(featureScores['Selected_Columns'][featureScores['Score']>0.01].tolist())

In [ ]:
select_list=['HOUSEID', 'HHFAMINC', 'WALK', 'TAXI', 'BUS', 'TRAIN', 'WALK2SAVE', 'BIKE2SAVE', 'PTRANS', 'HHRELATD', 'CNTTDHH',\
             'LIF_CYC', 'URBAN', 'URBANSIZE', 'HIGH_EDUC', 'HOMEOWN', 'WRKCOUNT_ratio',\
             'HHSIZE_cleaned', 'FT_ratio', 'AVG_WORK_DIST', 'one_job', 'flexible_work', 'DRVRCNTPROP_binned']

In [ ]:
# select_list=['HOUSEID', 'HHFAMINC', 'WALK', 'TAXI', 'BUS', 'TRAIN', 'WALK2SAVE', 'BIKE2SAVE', 'PTRANS', 'HHRELATD',\
#              'LIF_CYC', 'URBAN', 'URBANSIZE', 'HIGH_EDUC', 'HOMEOWN', 'WRKCOUNT_ratio', 'HHSIZE_cleaned',\
#              'FT_ratio', 'AVG_WORK_DIST', 'one_job', 'flexible_work', 'DRVRCNTPROP_binned']

In [ ]:
len(select_list)

In [ ]:
df = data_copy1[select_list]
df

In [ ]:
df.info()

In [ ]:
df['HHFAMINC'] =df['HHFAMINC'].astype('category')
df['WALK'] =df['WALK'].astype('category')
df['TAXI'] =df['TAXI'].astype('category')
df['BUS'] =df['BUS'].astype('category')
df['TRAIN'] =df['TRAIN'].astype('category')
df['WALK2SAVE'] =df['WALK2SAVE'].astype('category')
df['BIKE2SAVE'] =df['BIKE2SAVE'].astype('category')
df['PTRANS'] =df['PTRANS'].astype('category')
df['HHRELATD'] =df['HHRELATD'].astype('category')
df['LIF_CYC'] =df['LIF_CYC'].astype('category')
df['URBAN'] =df['URBAN'].astype('category')
df['URBANSIZE'] =df['URBANSIZE'].astype('category')
df['HIGH_EDUC'] =df['HIGH_EDUC'].astype('category')

In [ ]:
df.info()

In [ ]:
one_hot_col = [c for c in df if df[c].dtypes == 'O']

In [ ]:
one_hot_col

In [ ]:
#numeric variables: CNTTDHH, NUMADLT, YOUNGCHILD, WRKCOUNT
one_hot_col.extend(['HHFAMINC', 'HIGH_EDUC', 'URBANSIZE', 'URBAN', 'LIF_CYC', 'HHRELATD', 'PTRANS', 'BIKE2SAVE', 'WALK2SAVE', 'TRAIN', 'BUS', 'TAXI', 'WALK'])

In [ ]:
one_hot_col

In [ ]:
len(one_hot_col)

In [ ]:
df[one_hot_col].head(5)

In [ ]:
#df_one_hot = pd.get_dummies(df[one_hot_col], prefix = one_hot_col)

In [ ]:
df_one_hot = pd.get_dummies(df[one_hot_col])

In [ ]:
df = pd.concat([df, df_one_hot], axis = 1)

In [ ]:
df

In [ ]:
df.columns.tolist()

In [ ]:
df.shape

In [ ]:
df.to_csv('hh_final_one_hot_encoding.csv')